### PR TITLE
Added ability to split by mouse click, improved console log fomating and fixed some semicolons

### PR DESCRIPTION
**Pull request by ghost**
Added click to split feature (#74, thanks @Darkhand81 for suggesting it. It also woth with grazer. Simply you click the mouse button and it splits in a direction of your cursor. It's has good usage with grazer. I also improved the console logs, so better formating, and fixed some missing semicolons I can find arround.

### CODE REVIEW

**Comment by ghost** [comment]
The only think on this is that I need to update my blobs after splitting, so the grazer knows. But I dont know how to do that. Can somebody please help?

**Comment by RealDebugMonkey** [comment]
What makes you say it needs to be added to the list of owned blobs? The code shouldn't be needed. When we receive the update packet from the server it will be in the list of items we own.
Is it behaving oddly?

**Comment by Darkhand81** [comment]
I can say that when I try to use the grazer while split, it has trouble navigating.  It's most noticible when split into just two large blobs.  The two blobs don't seem to be aware of each other's presence and try to move through each other, which cancels out their movement and causes them to 'stall'. 

Movement is much smoother when split into several blobs, but with two they seem to interfere with one another.

**Comment by ghost** [comment]
@RealDebugMonkey The only thing i see its that on the splitted blob isnt the grazer visualizer... So if its ok, you can merge. @Darkhand81 I dont know, but that never happened to me.

**Comment by RealDebugMonkey** [comment]
@Darkhand81 The issue you describe is a slightly different issue. The problem is people want to add on features that I personally don't think the grazer has a good foundation for. I don't think that the split by mouse click will work the way people want it to because the mouse position and distance from your core cell has an impact on how far the split goes.

@PepinCZ Regardless, I'll hit the 'Merge pull request' button if you have tested change and it doesn't screw anything up.

**Comment by RealDebugMonkey** [comment]
To clarify: This feature people wanted is click-to-split so PepinCZ made it happen.

Whether the grazer behaves well after the split is a a whole different issue that goes into the food-chasing algorithm and is non-trivial to address.

**Comment by ghost** [comment]
@RealDebugMonkey ok, deleted the if isGrazer part and tested it one more time. It works good. I dont know if the feature is bad or no, but I think someone will use it. You can also do some tactics like going down with grazer then click and split all the way up. I think the enemy gets destroyed :+1:

**Comment by RealDebugMonkey** [comment]
Merged. Cross your fingers.

**Pull request merged**
