### PR TITLE
Fixed screen-freezing bug, added GitHub, Contrib and Zeach Cobbler skins

### PR DESCRIPTION
**Pull request by ghost**
Hello again,
I added ability to use GitHub avatar as your skins. Just use " ' " before your name... (Like this: 'PepinCZ). Its from GitHub's awesome API (https://avatars.githubusercontent.com/username).
I also added Contributors skins (as much contribs as I can find from our list), they uses GitHub avatars too. (For example, nick "RealDebugMonkey" will give his GitHub avatar). There is all contribs skins added: pepincz, realdebugmonkey, albel727, angal, apostolique, electronoob, heyitsleo, gjum, posixphreak. And I also added the Zeach Cobbler icon as a skin (nick Zeach Cobbler; ZeachCobbler). I know the icon is not perfect for skin, but I will create custom skin icon while I be able to go to my main PC.
So this is it, I know its small, but at least something :sweat_smile: 

And I fixed the minimap screen-freezing bug.. :smile_cat:

### CODE REVIEW

**Comment by RealDebugMonkey** [comment]
Cool. Thanks

**Comment by ghost** [comment]
@RealDebugMonkey nice to see you again. But please, pick some active person and give him merge permissions, or this project will be dead. Month inactivity in agar mod that needs quick updates is horrible.

**Comment by kaue** [comment]
@RealDebugMonkey Give the permission to @PepinCZ he earned it.

**Comment by Piehthyte** [comment]
@RealDebugMonkey I do agree! @PepinCZ deserves it ;p he has been working extremely hard as far as I have seen!

**Comment by jon-bullpoint** [comment]
Is the mini-map fix only a workaround, not a fix to the issue of the x,y coordinates being negative? I took a look at this and think at some point the x,y coords go negative (causing the exception) because parsing the data stream from agar.io gets messed up.

**Comment by ghost** [comment]
@jgilpin well yes, but how do you get the coors only positive? Maybe we need some minimap rewrite.

**Comment by jon-bullpoint** [comment]
Actually you are right, they can be negative. I just moved my blob to the top left of the map and looked at zeach.myPoints array, my only aa object has negative x,y coords. It probably is just an issue with the minimap. 

A separate issue, when you see 'frozen' blobs or food or viruses on the screen, they are no longer valid according to the server, but they remain in zeach.allItems. I've found it's possible to clear out those arrays, but the points on the map are only redrawn as you move around. I wonder why items aren't being destroyed properly?

**Comment by ghost** [comment]
@jgilpin well I don't know. Maybe some agar.io changes.

**Comment by ghost** [comment]
@jgilpin also my fix have nothing to do with the blobs being forever on minimap, math.abs only converts value into positive: http://www.w3schools.com/jsref/jsref_abs.asp

**Comment by jon-bullpoint** [comment]
Understood, just bringing up other off-topic issues :)

**Pull request merged**
